---
title: "Practice - FREE Workshop"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    toc_float: true
---

# About


<br />


This tutorial describes the basic workflow showing how to compute step by step
functional diversity (FD) indices in a multidimensional space. It is divided in 
four parts:

1. Computing trait-based distances and the multidimensional functional space 
2. Using the [`mFD`](https://github.com/CmlMagneville/mFD) package to compute 
FD alpha and beta indices and plot them 
([Magneville _et al._ 2021](https://doi.org/10.1111/ecog.05904))
3. Using the [`funrar`](https://github.com/rekyt/funrar) package to compute 
Functional Rarity indices 
([Violle _et al._ 2017](https://doi.org/10.1016/j.tree.2017.02.002))
4. Using the [`funbiogeo`](https://github.com/frbcesab/funbiogeo) package to 
compute analyses in functional biogeography 
([Violle _et al._ 2014](https://doi.org/10.1073/pnas.1415442111))


<br />


**N.B.** You can chose to do Part 2, Part 3 and Part 4 in the order that you want but 
Part 1 has to be realized first.


<br />
  
  
# Prerequisites

Be sure you have followed the [**instructions**](https://frbcesab.github.io/workshop-free/instructions.html)
to set up your system (e.g. `R version >= 3.5`).

If not already done, please install the following R packages: 



```{r echo=TRUE, eval=FALSE}
## CRAN packages ----
pkgs <- c("funrar", "mFD", "remotes", "sf", "terra")
install.packages(pkgs)

## GitHub packages ----
remotes::install_github("frbcesab/funbiogeo")
```


<br /> 
  
  
# Data description
  
The dataset used as study case all along this workshop is the **Fruits dataset** based on
`...` types of fruits (i.e. species) distributed in 10 fruits baskets (i.e. assemblages). 
Each fruit is characterized by `...` traits values summarized in the following table:
  
<br />
  
| Trait name   | Trait measurement  | Trait type    | Number of classes   | Classes code                       | Unit   |
|:------------:|:------------------:|:-------------:|:-------------------:|:----------------------------------:|:------:|
| Size         | Maximal diameter   | Ordinal       | 5                   | 0-1 ; 1-3 ; 3-5 ; 5-10 ; 10-20     | cm     |
| Plant        | Growth form        | Categorical   | 4                   | tree ; shrub ; vine ; forb         | NA     |
| Climate      | Climatic niche     | Ordinal       | 3                   | temperate ; subtropical ; tropical | NA     |
| Seed         | Seed type          | Ordinal       | 3                   | none ; pip ; pit                   | NA     |
| Sugar        | Sugar              | Continuous    | NA                  | NA                                 | g/kg   |
  
  
<br /> 
  

## Questions

...


